src/Cinrad.UI.Web/Controllers/ClienteController.cs
using Cinrad.Service.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Cinrad.UI.Web.Controllers
{
    [Authorize("RequireAdminRole")]
    public class ClienteController : BaseController
    {
        // GET: Cliente
        public IActionResult Index()
        {
            ViewBag.Clientes = Service.ClienteService.ObterTodos();
            return View();
        }

        // GET: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registrar(ClienteViewModel cliente)
        {           
            if (ModelState.IsValid)
            {

                var result = Service.ClienteService.Adicionar(cliente);
                if (!result)
                    ModelState.AddModelError(string.Empty, "Tentativa de cadastro falhou!");
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AssociarTransportadora(ClienteTransportadoraViewModel clienteTransportadora)
        {
            if(ModelState.IsValid)
            {
                if (!Service.ClienteTransportadora.Adicionar(clienteTransportadora))
                    ModelState.AddModelError(string.Empty, "Erro ao associar Transportador");
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(ClienteViewModel cliente)
        {
            if (ModelState.IsValid)
            {
                if (!Service.ClienteService.Atualizar(cliente))
                    ModelState.AddModelError(string.Empty, "Falha ao atualizar cadastro!");
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Cliente/Delete/5
        [HttpGet]        
        public IActionResult Remover(Guid id)
        {
            if (!Service.ClienteService.Remover(id))
                ModelState.AddModelError(string.Empty, "Falha ao excluir cadastro!");

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult RemoverTransportadora(ClienteTransportadoraViewModel clienteTransportadora)
        {
            if (ModelState.IsValid)
            {
                if (Service.ClienteTransportadora.Remover(clienteTransportadora))
                    return RedirectToAction(nameof(Index));                
            }

            return RedirectToAction(nameof(Index));
        }

        #region Partial
        [HttpGet]
        public IActionResult ClienteModal()
        {
            return PartialView();
        }

        [HttpGet]
        public IActionResult ClienteTransportadoraModal(Guid id)
        {
            var cliente = Service.ClienteService.ObterPorId(id);
            if (cliente == null)
                return PartialView();

            ViewBag.Transportadoras = new SelectList(Service.TransportadorService.ObterTodos(), "Id", "RazaoSocial");
            ViewBag.Id = cliente.Id;
            ViewBag.ClienteTransportadora = new SelectList(Service.ClienteTransportadora.ListarTransportadoras(id), "Id", "RazaoSocial");
            return PartialView();
        }

        [HttpGet]        
        public IActionResult EditarModal(Guid id)
        {
            var cliente = Service.ClienteService.ObterPorId(id);
            if (cliente == null)
                return PartialView();


            return PartialView(cliente);
        }

        [HttpGet]
        public IActionResult RemoverModal(Guid id)
        {
            var cliente = Service.ClienteService.ObterPorId(id);
            if (cliente != null)
                ViewBag.Id = cliente.Id;

            return PartialView();
        }
        #endregion
    }
}

src/Cinrad.UI.Web/Controllers/ProdutoController.cs
using Cinrad.Service.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Cinrad.UI.Web.Controllers
{
    [Authorize("RequireAdminRole")]
    public class ProdutoController : BaseController
    {
        public IActionResult Index()
        {           
            ViewBag.Produtos = Service.ProdutoService.ObterTodos();
            return View();
        }

        // GET: Produto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registrar(ProdutoViewModel produto)
        {
            if (ModelState.IsValid)
            {

                var result = Service.ProdutoService.Adicionar(produto);
                if (!result)
                    ModelState.AddModelError(string.Empty, "Tentativa de cadastro falhou!");
            }

            return RedirectToAction(nameof(Index));
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(ProdutoViewModel produto)
        {
            if (ModelState.IsValid)
            {
                if (!Service.ProdutoService.Atualizar(produto))
                    ModelState.AddModelError(string.Empty, "Falha ao atualizar cadastro!");
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Cliente/Delete/5
        [HttpGet]
        public IActionResult Remover(Guid id)
        {
            if (!Service.ProdutoService.Remover(id))
                ModelState.AddModelError(string.Empty, "Falha ao excluir cadastro!");

            return RedirectToAction(nameof(Index));
        }
        
        #region Partial
        [HttpGet]
        public IActionResult ProdutoModal()
        {
            return PartialView();
        }


        [HttpGet]
        public IActionResult EditarModal(Guid id)
        {
            var produto = Service.ProdutoService.ObterPorId(id);
            if (produto == null)
                return PartialView();


            return PartialView(produto);
        }


        [HttpGet]
        public IActionResult RemoverModal(Guid id)
        {
            var produto = Service.ProdutoService.ObterPorId(id);
            if (produto != null)
                ViewBag.Id = produto.Id;

            return PartialView();
        }

        #endregion
    }

}

src/Cinrad.UI.Web/Controllers/TransportadorController.cs
using Cinrad.Service.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Cinrad.UI.Web.Controllers
{
    [Authorize("RequireAdminRole")]
    public class TransportadorController : BaseController
    {

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Transportadoras = Service.TransportadorService.ObterTodos();
            return View();
        }

        // GET: Transportador/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Registrar(TransportadoraViewModel transportadora)
        {
            if (ModelState.IsValid)
            {
                var result = Service.TransportadorService.Adicionar(transportadora);
                if (!result)
                    ModelState.AddModelError(string.Empty, "Tentativa de cadastro falhou!");
            }           

            return RedirectToAction(nameof(Index));
        }        

        // POST: Transportador/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(TransportadoraViewModel transportadora)
        {
            if (ModelState.IsValid)
            {
                if (!Service.TransportadorService.Atualizar(transportadora))
                    ModelState.AddModelError(string.Empty, "Falhou! ao atualizar cadastro!");
            }            

            return RedirectToAction(nameof(Index));
        }

        // GET: Transportador/Delete/Id
        [HttpGet]       
        public IActionResult Remover(Guid id)
        {
            if (!Service.TransportadorService.Remover(id))
                ModelState.AddModelError(string.Empty, "Falha ao excluir cadastro!");

            return RedirectToAction(nameof(Index));
        }     


        #region Partial
        [HttpGet]
        public IActionResult TransportadorModal()
        {
            return PartialView();
        }        

        
        [HttpGet]
        public IActionResult EditarModal(Guid id)
        {
            var transportadora = Service.TransportadorService.ObeterPorId(id);
            if (transportadora == null)
                return PartialView();

            return PartialView(transportadora);
        }

        [HttpGet]
        public IActionResult RemoverModal(Guid id)
        {
            var cliente = Service.TransportadorService.ObeterPorId(id);
            if (cliente != null)
                ViewBag.Id = cliente.Id;

            return PartialView();
        }
        #endregion
    }
}

src/Cinrad.UI.Web/Controllers/UsuarioController.cs
using Cinrad.Service.ViewModels;
using Cinrad.UI.Web.Models.AccountViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Cinrad.UI.Web.Controllers
{
    [Authorize("RequireAdminRole")]
    public class UsuarioController : BaseController
    {

        [HttpGet]
        public IActionResult Index(bool status = true)
        {            
            var users = Service.UsuarioService.ObterTodos();
            ViewBag.Usuarios = users.Where(c => c.IsAtivo == status).ToList();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registrar(UsuarioViewModel usuario, int perfil)
        {
            if (ModelState.IsValid)
            {
                var result = await Service.UsuarioService.Adicionar(usuario, perfil);
                if (!result)
                    ModelState.AddModelError(string.Empty, "Tentativa de cadastro falhou!");                
            }           

            return RedirectToAction(nameof(Index), ModelState);
        }

        [HttpGet]
       // [ValidateAntiForgeryToken]
        public IActionResult Perfil(Guid id)
        {
            var user = Service.UsuarioService.ObterPorId(id);
            ViewBag.User = user;
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(UsuarioViewModel usuario, RegisterViewModel register = null, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var result = Service.UsuarioService.Atualizar(usuario);
                if (!result)
                    ModelState.AddModelError(string.Empty, "Falha ao atualizar cadastro!");
            }

            if(!string.IsNullOrEmpty(returnUrl))
               return RedirectToAction(nameof(Perfil), usuario);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Remover(Guid id)
        {
            if (!Service.UsuarioService.Remover(id))
                ModelState.AddModelError(string.Empty, "Falha ao excluir cadastro!");

            return RedirectToAction(nameof(Index));
        }

        #region Partial
        [HttpGet]
        public ActionResult UsuarioModal()
        {

            ViewBag.Transportadoras = new SelectList(Service.TransportadorService.ObterTodos(), "Id", "RazaoSocial");
            ViewBag.Clientes = new SelectList(Service.ClienteService.ObterTodos(), "Id", "RazaoSocial");

            return PartialView();
        }

        [HttpGet]
        public IActionResult EditarModal(Guid id)
        {
            var user = Service.UsuarioService.ObterPorId(id);
            if (user == null)
                return PartialView();

            ViewBag.Transportadoras = new SelectList(Service.TransportadorService.ObterTodos(), "Id", "RazaoSocial");
            ViewBag.Clientes = new SelectList(Service.ClienteService.ObterTodos(), "Id", "RazaoSocial");
            
            return PartialView(user);
        }

        [HttpGet]
        public IActionResult PerfilModal(Guid id, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            var user = Service.UsuarioService.ObterPorId(id);
            if (user == null)
                return PartialView();           
           
            return PartialView(user);
        }

        [HttpGet]
        public IActionResult RemoverModal(Guid id)
        {
            var user = Service.UsuarioService.ObterPorId(id);
            if (user != null)
                ViewBag.Id = user.Id;


            return PartialView();
        }
        #endregion
    }
}

src/Cinrad.UI.Web/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        Brasil <strong>SP</strong>
    </div>
    <div>
        <strong>Copyright</strong> JHealth Company &copy; 2019
    </div>
</div>

src/Cinrad.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Cinrad</title>

    <environment include="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Morris -->
        <link href="~/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

        <!-- Gritter -->
        <link href="~/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

        <link href="~/css/animate.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">

        <!-- Data Tables -->
        <link href="~/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
        <link href="~/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
        <link href="~/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">


        <!-- multiselect -->
        <link href="~/css/plugins/chosen/chosen.css" rel="stylesheet">

        <link href="~/css/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet">
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Morris -->
        <link href="~/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

        <!-- Gritter -->
        <link href="~/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

        <link href="~/css/animate.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">

        <!-- Data Tables -->
        <link href="~/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
        <link href="~/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
        <link href="~/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">


        <!-- multiselect -->
        <link href="~/css/plugins/chosen/chosen.css" rel="stylesheet">

        <link href="~/css/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @await Html.PartialAsync("_Navigation")
        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Top Navbar -->
            @await Html.PartialAsync("_TopNavbar")

            <!-- Main view  -->

            @RenderBody()

            <!-- Footer -->
            @await Html.PartialAsync("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->
    
    <environment include="Development">
        <!-- Mainly scripts -->
        <script src="~/js/jquery-2.1.1.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/plugins/metisMenu/jquery.metisMenu.js"></script>
        <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
        <script src="~/js/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>
        <script src="js/plugins/clockpicker/clockpicker.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/jquery-clockpicker.min.css"></script>
  
     

        <!-- Flot -->
        <script src="~/js/plugins/flot/jquery.flot.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.spline.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.resize.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.pie.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.symbol.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.time.js"></script>

        <!-- Peity -->
        <script src="~/js/plugins/peity/jquery.peity.min.js"></script>
        <script src="~/js/demo/peity-demo.js"></script>

        <!-- Custom and plugin javascript -->
        <script src="~/js/inspinia.js"></script>
        <script src="~/js/plugins/pace/pace.min.js"></script>

        <!-- jQuery UI -->
        <script src="~/js/plugins/jquery-ui/jquery-ui.min.js"></script>

        <!-- Jvectormap -->
        <script src="~/js/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js"></script>
        <script src="~/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

        <!-- EayPIE -->
        <script src="~/js/plugins/easypiechart/jquery.easypiechart.js"></script>

        <!-- Sparkline -->
        <script src="~/js/plugins/sparkline/jquery.sparkline.min.js"></script>

        <!-- Sparkline demo data  -->
        <script src="~/js/demo/sparkline-demo.js"></script>

    </environment>
    <environment exclude="Development">
        <!-- Mainly scripts -->
        <script src="~/js/jquery-2.1.1.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/plugins/metisMenu/jquery.metisMenu.js"></script>
        <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
        <script src="~/js/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>

        <!-- Flot -->
        <script src="~/js/plugins/flot/jquery.flot.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.spline.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.resize.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.pie.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.symbol.js"></script>
        <script src="~/js/plugins/flot/jquery.flot.time.js"></script>

        <!-- Peity -->
        <script src="~/js/plugins/peity/jquery.peity.min.js"></script>
        <script src="~/js/demo/peity-demo.js"></script>

        <!-- Custom and plugin javascript -->
        <script src="~/js/inspinia.js"></script>
        <script src="~/js/plugins/pace/pace.min.js"></script>

        <!-- jQuery UI -->
        <script src="~/js/plugins/jquery-ui/jquery-ui.min.js"></script>

        <!-- Jvectormap -->
        <script src="~/js/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js"></script>
        <script src="~/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

        <!-- EayPIE -->
        <script src="~/js/plugins/easypiechart/jquery.easypiechart.js"></script>

        <!-- Sparkline -->
        <script src="~/js/plugins/sparkline/jquery.sparkline.min.js"></script>

        <!-- Sparkline demo data  -->
        <script src="~/js/demo/sparkline-demo.js"></script>
        
    </environment>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/metsiMenu")
    @Scripts.Render("~/plugins/pace")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")*@
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Cinrad.UI.Web/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img src="~/img/logo-hc.png" />
                    </span>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a asp-area="" asp-controller="Account" asp-action="Index">Inicio</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    HC
                </div>
            </li>
            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-clock-o"></i> <span class="nav-label">Agenda de Produções</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Pedidos</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Home" asp-action="Calculadora"><i class="fa fa-calculator"></i><span class="nav-label">Calculadora</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Produto" asp-action="Index"><i class="fa fa-flask"></i> <span class="nav-label">Produtos</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Transportador" asp-action="Index"><i class="fa fa-truck"></i> <span class="nav-label">Transportadoras</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Cliente" asp-action="Index"><i class="fa fa-users"></i> <span class="nav-label">Clientes</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Usuario" asp-action="Index"><i class="fa fa-desktop"></i> <span class="nav-label">Usuários</span></a>
            </li>

            <li>
                <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-bell"></i> <span class="nav-label">Alertas</span></a>
            </li>

            <li>
                <a href="#" t="widgets.html"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Relatórios</span><span class="fa arrow"></span></a>

                <ul class="nav nav-second-level collapse">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Painel</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Pedidos</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Produção</a></li>
                </ul>

            </li>

            <li>
                <a href="#" t="widgets.html"><i class="fa fa-gears"></i> <span class="nav-label">Administração</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Parâmetros</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Auditoria</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

src/Cinrad.UI.Web/Views/Shared/_TopNavBar.cshtml
@using Cinrad.Infrastructure.CrossCutting.Identity
@inject SignInManager<ApplicationUser> SigninManager
@inject UserManager<ApplicationUser> UserManager

<div class="row border-bottom">
    <nav class="navbar navbar-static-top blue-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="" class="form-control" name="top-search" id="top-search" value="CICLOTRON - INRAD" readonly>
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            @if (SigninManager.IsSignedIn(User))
            {
            
                @*<li class="dropdown">
                    <a class="dropdown-toggle count-info" style=" color: white" data-toggle="dropdown" href="#" t="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#" t="mailbox.html">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#" t="profile.html">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#" t="grid_options.html">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="#" t="notifications.html">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>*@
                <li>
                    <a asp-area="" asp-controller="Usuario" asp-action="Perfil" asp-route-id="@UserManager.GetUserId(User)" style=" color: white">@UserManager.GetUserName(User)</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Account" asp-action="Logout" style=" color: white"><i class="fa fa-sign-out"></i> <span class="nav-label">Sair</span></a>
                </li>
            }
            else
            {

                <li>
                    <a asp-area="" asp-controller="Account" asp-action="Login" style=" color: white"><i class="fa fa-sign-in"></i> <span class="nav-label">Entrar</span></a>
                </li>
            }
        </ul>

    </nav>
</div>